### ISSUE TITLE
Create Procedure still broken (AL version 8.2.545335)

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [DavidFeldhoff/al-codeactions#133]
The issue marked as resolved in #132 is still not working.
![image](https://user-images.githubusercontent.com/30231314/142884072-9d976ea0-f634-4146-a64c-92cffcaf0ea7.png)
AL version: v8.2.545335
AL CodeActions version: v1.0.10

For some time it workaround downgrading extension version was working but not anymore (have no idea why). If there is anything else I could provide (some sort of a log) - just let me know.

**Comment by nickgoddard777** [comment]
AL version: v8.1.540594
AL CodeActions: v1.0.10

If I try and use the Create Procedure code action I get an error in the bottom right saying 'illegal value for 'line''

![image](https://user-images.githubusercontent.com/332366/142894573-cd9ec229-d823-44f1-8a17-d60c7772eed1.png)

**Comment by DavidFeldhoff** [comment]
Thanks to both of you!
I've just uploaded a new version which should fix it. The issue was that Microsoft has a new JSON format of the diagnostics/warnings. I considered that in #132. But somehow they are sending sometimes the new format and sometimes the old format in version 8.2.545335. Didn't see that coming.. I am considering that now, so it should work now again @AndriusAndrulevicius .

@nickgoddard777: That does **not** explain your issue in my eyes. If the issue still persists in version 1.0.11 (which I think), then please provide some more detail like
- what your code looks like 
- if it happens everytime
- if it's fixed with the newest AL language version

Cheers
David

**Comment by AndriusAndrulevicius** [comment]
I think I found the source of my initial problem:
![image](https://user-images.githubusercontent.com/30231314/142983887-43188bd4-1a00-4344-ab1b-0861f33f6892.png)
If I remove the line with the comment (line 13) I get suggestions to create procedures. But if I try with the line 13 - it gives only suggestions as per my original screen shot.

**Comment by DavidFeldhoff** [comment]
Hi Andrius,
I could reproduce that if you're trying to "add a parameter" or "create a procedure overload" and you have a comment line before that, that the code action was not showing up. I've fixed it and it should work in version 1.0.12. I hope you can verify that.
Cheers
David

**Comment by AndriusAndrulevicius** [comment]
tested with 1.0.12 - at least for me it's not working (might be something on my machine).
Steps to reproduce (the screenshot above):
1. Create call to the procedure.
2. Cretate procedure using CodeAction
3. Add a comment line.
4. Create call to an overloaded procedure - at this point CodeActions don't show anything except pragma.

**Comment by nickgoddard777** [comment]
@DavidFeldhoff Thanks for your prompt reply (and for such a good tool).  I have upgraded your extension to the latest version v1.0.12. still no luck.  I have also upgraded AL Language to v8.2.545335 and I still get the same issue.  I have tried a clean install that has hardly any settings, and only the following extensions and it works Ok there:
AL CodeActions
AL Language
AL Navigator
AZ AL Dev Tools/AL Code Outline
waldo's CRS aL Language Extension.
The reason I have this and the reason on my dev machine I had downgraded AL Language was to help with AL Navigator as the code actions on there aren't working with the latest AL Language,

I guess therefore my issue is an Extension or a setting.  I'll try and disable some to try and find where the issue is.

**Comment by DavidFeldhoff** [comment]
> tested with 1.0.12 - at least for me it's not working (might be something on my machine). Steps to reproduce (the screenshot above):
> 
> 1. Create call to the procedure.
> 2. Cretate procedure using CodeAction
> 3. Add a comment line.
> 4. Create call to an overloaded procedure - at this point CodeActions don't show anything except pragma.

That is exactly what I've tested..
AL CodeActions Version v1.0.12
AL Language Extension Version v8.2.545335
You can see my result here: https://user-images.githubusercontent.com/53570297/143006941-fac83f70-1f7a-47ce-8956-7f03bc3ad62c.mp4

Are there any settings set? Or are you doing it somehow different then me? Maybe you can show me a screen recording as well. (I'm using [ScreenToGif](https://www.screentogif.com/) if that helps)

But maybe it is the same issue that @nickgoddard777 experiences. As far as I understood him it works fine in a clean installation, but not with his "final setup". Then it seems that there is some other extension, some specific setting that crashes.. I hope you can help me finding it by getting it reproduced!

**Comment by nickgoddard777** [comment]
This is strange, I deleted all my extensions, and all my settings.  I then installed AL Language and AL CodeActions (which also installed AZ AL Dev Tools and Waldos extension).  Still didn't work.

Opened a different project and it worked, so it must be an issue somewhere in my current project.

***I've worked it out, it is just an issue in the current Report I'm working on.  I wonder if I've got something in the wrong order and therefore the CreateProcedure is getting stuck.

**Comment by DavidFeldhoff** [comment]
Could you please find out what it is exactly, so that I can fix it right away?

**Comment by nickgoddard777** [comment]
That took a lot of working out. There was a blank line after the final curly bracket in my report.  I've deleted that and it now works.

![image](https://user-images.githubusercontent.com/332366/143054422-f0507947-98e1-46bb-b197-f0c25ef2a883.png)

**Comment by DavidFeldhoff** [comment]
Oh no. Sorry for that. I've fixed it right away. 
I'm waiting for @AndriusAndrulevicius if he can give me some more details as well why it's not working for him, so that I can publish both issues in the same release, because it would definetely be another issue (as you were seeing the code action and got the error on executing it while Andrius isn't able to see the code action at all)

**Comment by AndriusAndrulevicius** [comment]
I no longer can reproduce the issue - sorry for the delay

**Comment by DavidFeldhoff** [comment]
Okay, then I've released the version 1.0.13.
@nickgoddard777 If you can confirm that the bug was fixed, I'll close this issue.
@AndriusAndrulevicius If you encounter the issue once more, I'd glad if you contact me again :) But I think I've fixed the issue. Maybe there was a "reload window" missing after my extension was updated or something like that, so that the extension management page showed the version 1.0.12, but still worked with 1.0.11.

Thanks to both of you for contributing :)

**Comment by nickgoddard777** [comment]
@DavidFeldhoff Yes that is working for me now.

Thanks very much :)

**Comment by DavidFeldhoff** [comment]
Awesome. Thanks for verifying! And thanks for your review at the marketplace 🥳
